### ISSUE TITLE
Missing pixel formats when switching from legacy drivers to IC4

### ISSUE THREAD

**Issue by kparent60** [TheImagingSource/ic4-examples#26]
Hi,

I have a question related to the pixel formats for the new IC4 drivers. We are currently doing the switch from the 'IC Imaging Control C++ class library' to the newest 'IC Imaging Control 4'.

We are currently integrating the library into our Qt C++ code and everything is going well so far.

The issue I am facing is the pixel formats of this new library. Before switching, we were creating a QImage with the buffer received from the _framesQueued_ callback. We used the format [_Format_RGB32_](https://doc.qt.io/qt-6/qimage.html#:~:text=into%20a%20colormap.-,QImage%3A%3AFormat_RGB32,-4) to create the image. This format seems to be non existent now or might have been renamed/repackaged (?). I returned the enumeration entries for both the DFK33UX290 and the DFK33UX273 and this is what I got :

**DFK33UX273** 
`"Entries :" QList("Mono8", "BayerRG8", "BayerRG12p", "BayerRG16", "YCbCr422_8", "YCbCr411_8", "YCbCr411_8_CbYYCrYY", "BGR8")`

**DFK33UX290** 
`"Entries :" QList("Mono8", "BayerRG8", "BayerRG16", "BGR8", "YCbCr422_8", "YCbCr411_8", "YCbCr411_8_CbYYCrYY")`

When using IC capture with the old drivers, I get those (for DFK33UX273) :
![image](https://github.com/user-attachments/assets/f9e26756-6d88-4301-b1a6-f2a573c6b973)

Do you know which pixel format I should use to have the same RGB32 format I had before? And also, do you know how it should be done using QImage?

Thank you in advance for your guidance and your help,
Keven

**Comment by TIS-Tim** [comment]
The DirectShow driver augmented the video format lists provided by the device, and RGB32 was a format created from transmitting Bayer8 and performing software transformations in the driver.

In IC4, the PixelFormat feature selects what is actually transmitted over the wire. If you want to have images as RGB32 in your program (e.g. to run some image processing on them, the easiest was is to set a pixel format for the sink. IC4 will then automatically transform the image data from the camera format to the requested buffer format. An example for this can be seen [here](https://github.com/TheImagingSource/ic4-examples/blob/master/cpp/thirdparty-integration/imagebuffer-opencv-snap/src/imagebuffer-opencv-snap.cpp#L27). The pixel format value to request RGB32 is `BGRa8`.

Please note that you do not necessarily need to do this at all, since all ic4 functions that are consuming image buffers (e.g. functions to save images or videos, displaying images, and most third-party library interop functions) do a transformation on demand.

**Comment by kparent60** [comment]
WOW. Thank you so much. I completely missed that you could do that with the sinks. I am now getting the images in my RGB32 format as I wanted. Props to you also for the fast answer.

Keven
